packages:
  - 'packages/*'
  - 'examples/*'
  - 'website'

allowBuilds:
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  puppeteer: set this to true or false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild