name: CLI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check and build codebase
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        output-types: ['tsx', 'jsx', 'onepage']
        output-project-types: ['tsx', 'jsx']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('./pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build CLI
        run: pnpm run build:cli

      - name: Install ts-node
        run: sudo npm install -g ts-node

      - name: Move into cli package
        run: cd ./packages/cli/

      - name: Create ${{ matrix.output-types }} example project
        run: ts-node ./src/cli.ts -t ${{ matrix.output-types }} -n example-${{ matrix.output-types }}

      - name: Install dependencies for example-${{ matrix.output-project-types }} example project
        run: cd ./example-${{ matrix.output-project-types }} && pnpm install

      - name: Start example-${{ matrix.output-project-types }} project
        run: pnpm start
