name: Spectacle Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      repository-projects: write
      deployments: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 7

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 18.x

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          # Note: Our `package.json:scripts.version` currently doesn't have `--fix-lockfile` for
          # `pnpm install` because of a PNPM bug of some kind.
          # https://github.com/FormidableLabs/spectacle/issues/1156
          version: pnpm run version
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
